// 这里统一存放action常量

// auth.js
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';

// menu.js
export const MENUS_REQUEST = 'MENUS_REQUEST';
export const MENUS_SUCCESS = 'MENUS_SUCCESS';
export const MENUS_FAILURE = 'MENUS_FAILURE';

// roles.js
export const ROLES_REQUEST = 'ROLES_REQUEST';
export const ROLES_SUCCESS = 'ROLES_SUCCESS';
export const ROLES_FAILURE = 'ROLES_FAILURE';
export const ABILITIES_REQUEST = 'ABILITIES_REQUEST';
export const ABILITIES_SUCCESS = 'ABILITIES_SUCCESS';
export const ABILITIES_FAILURE = 'ABILITIES_FAILURE';

// purchaseOrders.js
export const PURCHASE_ORDERS_REQUEST = 'PURCHASE_ORDERS_REQUEST';
export const PURCHASE_ORDERS_SUCCESS = 'PURCHASE_ORDERS_SUCCESS';
export const PURCHASE_ORDERS_FAILURE = 'PURCHASE_ORDERS_FAILURE';


// purchaseOrderItem.js
export const PURCHASE_ORDER_ITEMS_REQUEST = 'PURCHASE_ORDER_ITEMS_REQUEST';
export const PURCHASE_ORDER_ITEMS_SUCCESS = 'PURCHASE_ORDER_ITEMS_SUCCESS';
export const PURCHASE_ORDER_ITEMS_FAILURE = 'PURCHASE_ORDER_ITEMS_FAILURE';
